version: '3.8'

services:
  fastapi-app:
    image: fastapi-app
    container_name: fastapi-container
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
    volumes:
      - ./app:/app
