name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t fastapi-app .

    - name: Run tests inside Docker container
      run: |
        docker run --rm -e PYTHONPATH=/app fastapi-app pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decode SSH Key and Save
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to Known Hosts
      run: ssh-keyscan -H 3.145.168.139 >> ~/.ssh/known_hosts

    - name: SSH into EC2 and Deploy
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@3.145.168.139 << 'EOF'
          echo "Connected to EC2"
          cd /home/ec2-user/fastapi-app
          git pull origin master
          docker-compose down || true
          docker-compose up -d --build
        EOF
