name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to `master` instead of `main`
  pull_request:
    branches:
      - master  # Also update this to `master`

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t fastapi-app .

    - name: Run tests inside Docker container
      run: |
        docker run -e PYTHONPATH=/app fastapi-app pytest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'  # Update to check for `master`

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/fastapi-app
          git pull origin master  # Pull from `master`
          docker-compose down
          docker-compose up -d
